"""REST collision sweep — regression guard.

``detection.sweep`` synthesizes the minimal request each REST operation's
model declares and checks the matcher resolves it back to itself. The
committed snapshot (``fidelity/rest_sweep.json``, regenerated by
``tools/rest_sweep.py``) is the contract: ops that self-resolve must keep
self-resolving, and the ambiguous set must not grow.

The 5 unresolved ops are genuine AWS aliases — ``GetBucketLifecycle`` and
``GetBucketLifecycleConfiguration`` share the literal ``GET /{Bucket}?
lifecycle`` route (even AWS can't tell them apart), and
``ListDirectoryBuckets``/``ListBuckets`` are both bare ``GET /`` (real AWS
separates them by host, not path).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from botocore.session import Session

from microburst.detection.sweep import sweep_service

SNAPSHOT = Path(__file__).resolve().parent.parent / "fidelity" / "rest_sweep.json"

_session = Session()
_REST_SERVICES = sorted(
    svc
    for svc in _session.get_available_services()
    if _session.get_service_model(svc).protocol in ("rest-json", "rest-xml")
)


def test_sweep_snapshot_file_is_current():
    """The committed snapshot must match a fresh sweep — regenerate with
    ``python tools/rest_sweep.py`` after intentional matcher changes."""
    from microburst.detection.sweep import sweep_all

    current = sweep_all()
    expected = json.loads(SNAPSHOT.read_text())
    assert current == expected, (
        "REST sweep drifted from fidelity/rest_sweep.json — "
        "regenerate with tools/rest_sweep.py and review the diff"
    )


@pytest.mark.parametrize("service", _REST_SERVICES, ids=_REST_SERVICES)
def test_ambiguous_ops_do_not_grow(service):
    """Every op resolves to itself, or is in the documented ambiguous set
    for that service. The set must only ever shrink."""
    snapshot = json.loads(SNAPSHOT.read_text())
    expected = snapshot.get(service, {})
    ambiguous = {op for op, got in expected.items() if got != op}
    current = sweep_service(service)
    for op, resolved in current.items():
        if op in ambiguous:
            continue
        assert resolved == op, (
            f"{service}.{op} resolved to {resolved!r} — new ambiguity "
            "needs reviewing (add to snapshot only if truly unresolvable)"
        )
