"""Fidelity regression gate: the committed live-AWS goldens must still
match what the serializers render today.

``fidelity/REPORT.md`` is generated by hand (``microburst fidelity
report``); this test runs the identical comparison
(``fidelity.check_capture``) inside pytest so a serializer drift fails CI
instead of silently rotting the goldens. No network, no credentials —
pure render-vs-capture comparison.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from botocore.session import Session

from microburst.fidelity import _is_success, check_capture

_CAPTURES_DIR = Path(__file__).resolve().parent.parent / "fidelity" / "captures"


def _load(path: Path) -> dict:
    return json.loads(path.read_text())


# success-path captures share the directory but microburst never renders
# 2xx bodies — the gate only makes sense for error captures.
_CAPTURES = [
    p for p in sorted(_CAPTURES_DIR.glob("*.json"))
    if not _is_success(_load(p))
]
_FIELDS = ("status_ok", "code_ok", "ct_ok", "shape_ok")

_session = Session()


def test_capture_floor():
    """A deleted capture must shrink the gate loudly, not silently."""
    assert len(_CAPTURES) >= 28, (
        f"only {len(_CAPTURES)} error captures in {_CAPTURES_DIR} — "
        "the golden set shrank; restore the deleted probe(s)"
    )


def test_gate_parametrizes_error_captures_only():
    """Every parametrized golden must be an error capture — success
    probes (status < 400 / ``kind: "success"``) are compared by
    conform/diff, never rendered."""
    assert _CAPTURES, "gate parametrizes nothing"
    for p in _CAPTURES:
        cap = _load(p)
        assert not _is_success(cap), f"{p.name} is a success capture"
        assert cap.get("sdk_error_code"), f"{p.name} has no error code"


@pytest.mark.parametrize(
    "path", _CAPTURES, ids=[p.stem for p in _CAPTURES]
)
def test_golden_matches_rendered_error(path: Path):
    """status + parsed Error.Code + Content-Type + envelope shape."""
    r = check_capture(_load(path), _session)
    label = f"{r['service']}.{r['operation']} (`{r['code']}`)"
    detail = r["detail"]
    assert r["status_ok"], (
        f"{label}: status AWS {r['real_status']} vs ours {r['ours_status']}"
    )
    assert r["code_ok"], f"{label}: parsed Error.Code differs"
    assert r["ct_ok"], (
        f"{label}: content-type AWS `{r['real_ct']}` "
        f"vs ours `{r['ours_ct']}`"
    )
    assert r["shape_ok"], (
        f"{label}: envelope AWS `{detail['real_sig']}` "
        f"vs ours `{detail['ours_sig']}`"
    )


def test_all_goldens_pass():
    """The full committed set must pass — the report's 28/28 line,
    enforced as a single gate."""
    failures = []
    for path in _CAPTURES:
        r = check_capture(_load(path), _session)
        bad = [f.removesuffix("_ok") for f in _FIELDS if not r[f]]
        if bad:
            failures.append(f"{path.stem} ({', '.join(bad)})")
    assert not failures, (
        f"{len(failures)}/{len(_CAPTURES)} goldens drifted from "
        f"render_error: {'; '.join(failures)}"
    )
